### ISSUE TITLE
Error with DevOps task, doesn't occur when running release-flow locally from the command line

### ISSUE THREAD

**Issue by ScottLeWarne** [release-flow/azure-pipelines-extension#20]
Hi, I'm having an issue with the release-flow pipelines extension throwing an error.  When I run the release-flow command line against the same repo it runs fine and prints correct output.  But within DevOps pipeline I get this:

##[error]Error: Error calling 'git log': fatal: ambiguous argument '6e3abde501130c679ec80ab59884b9da498d63c2..origin/main': unknown revision or path not in the working tree.

This is what I have for configuration in the yaml.
Also, am using v0.1.0

![image](https://github.com/release-flow/azure-pipelines-extension/assets/5997637/797433ba-511f-49e6-9209-24d414cd61bb)

**Comment by ScottLeWarne** [comment]
Was able to resolve this, it was related to how Azure Pipelines was checking out the git repo by default.

**Comment by richtea** [comment]
Hi @ScottLeWarne thanks for the report, and also for updating that you fixed it! What did you do to resolve the DevOps checkout issue? Just in case anyone else has the same issue.

**Comment by ScottLeWarne** [comment]
Sorry, should have included that.

On the 'checkout' configuration within the pipeline yaml I added the last three lines.  I'm not positive which one did it, might be a combination.

![image](https://github.com/release-flow/azure-pipelines-extension/assets/5997637/5b6b0c4d-5dac-4af5-9e42-a4e83d0d3324)

**Comment by richtea** [comment]
Thanks for the additional info Scott. I'd guess the `fetchTags: true` fixed it, the error message looked like it was unable to recognise `origin/main` for some reason. Glad you're up and running, anyway!
