### ISSUE TITLE
Update documentation for usage in azure-pipelines

### ISSUE THREAD

**Issue by miniGweek** [release-flow/azure-pipelines-extension#21]
Since September 2022, Azure Pipeline does a shallow fetch of the git repo. 
This breaks release-flow extension, as well as the `rfver` package.
See Microsoft documentation @ https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#shallow-fetch

We have to set the `fetchDepth` value to 0 in the checkout step explicitly for `release-flow` to work.

**Comment by richtea** [comment]
Thanks for the information @miniGweek I will update the docs when I return from my vacation in a couple of weeks.
